### ISSUE TITLE
[Bug] - Rehype tag error 

### ISSUE THREAD

**Issue by sktbrd** [SkateHive/nextskateapp#10]
## Description
When I attempt to include HTML directly within Markdown content using rehype, the application crashes. This issue occurs every time I add HTML tags in the middle of the Markdown text.

## Steps to Reproduce
1. Open + Create Post Page
2. Insert an HTML element (e.g., `<div>Test</div>`) into the Markdown in the middle of the text
3. Observe that the application crashes or does not render properly.

## Expected Behavior
I expect that HTML inserted within Markdown should be rendered correctly without causing any crashes or rendering issues.

## Actual Behavior
Inserting HTML causes the application to crash or fail to render the content correctly.

![Screen Recording May 1](https://github.com/SkateHive/nextskateapp/assets/116202536/d99f17f3-8c56-4c4d-b7ac-faa5d1d281d0)

## Possible Solution
N/A - I am not sure what is causing the issue, any insights or workarounds would be appreciated.

## Additional Information

If you disable rehypePlugiins the error is fixed, but then we lose <video> and <iframe> tags rendering 

![image](https://github.com/SkateHive/nextskateapp/assets/116202536/5f4ca26e-6f52-4281-b5c4-57c274848dda)
> src/app/upload/page.tsx

**Comment by webgnar** [comment]
return to this later
