### ISSUE TITLE
[Bounty] - Plaza Page Desktop and Mobile 

### ISSUE THREAD

**Issue by sktbrd** [SkateHive/nextskateapp#2]
### Title: Enhance Mobile User Experience for Plaza Page on Skatehive

# What is Plaza Page

The plaza page is the microblogging solution of skatehive, inspired in Twitter, inLeo and Warpcast, that was our first attempt of a microblogging experience for our user. 

Check the current versions of plaza: 
- https://skatehive.app/plaza 
- https://skate-six.vercel.app 

### Description:

We are seeking to revamp the user experience of the Plaza page on Skatehive, our microblogging platform inspired by Twitter, inLeo, and Warpcast. This enhancement focuses particularly on optimizing the mobile interface, drawing inspiration from Instagram Stories for a seamless browsing and posting experience on mobile devices. The goal is to make Plaza the centerpiece of the mobile experience, ensuring users can effortlessly create content similar to filming Instagram stories, but tailored to skate culture.

#### Requirements:

1. **Mobile-First Design:** 
   - Implement a user-friendly mobile interface where Plaza acts as the main page.
   - Enable users to post content with just one click, akin to Instagram Stories.
   - Incorporate a camera feature that resonates with skate culture, enhancing the content creation process.

2. **Desktop Interface:**
   - Maintain a Twitter-like interface for desktop users, focusing on readability and easy navigation.

3. **API Integration:**
   - Coordinate with Vlad to obtain the IPFS API key. If unavailable, secure a free one from an appropriate provider to ensure proper backend integration.

#### Evaluation Criteria:

- **User Interface Design:** The design should be intuitive, engaging, and cater specifically to the needs of mobile users while maintaining functionality on desktop.
- **Functionality:** Seamless integration of features such as the skate culture camera and one-click posting.
- **Performance:** The Plaza page should load quickly and efficiently, with smooth transitions and minimal latency.

#### Deliverables:

- A fully functional mobile version of the Plaza page that aligns with the Instagram Stories format.
- An updated desktop version that preserves the essence of the traditional microblogging experience.
- Integration of the IPFS API for robust backend functionality.

Please ensure that both the desktop and mobile versions are thoroughly tested for usability and functionality before final submission.

#### Additional Information:

To access necessary resources or if you encounter any issues regarding API integration, please contact Vlad at your earliest convenience.

---

## Bounty: 150 USDC

**Comment by abhisheknaiidu** [comment]
@sktbrd can i pick this?
