### ISSUE TITLE
[Bounty] - Develop a Multichain Wallet Page for SkateHive

### ISSUE THREAD

**Issue by sktbrd** [SkateHive/nextskateapp#4]
### Description:

We are inviting developers to build a comprehensive multichain wallet page for SkateHive users. This new wallet page should support both Hive and Ethereum (ETH) blockchains and provide a user-friendly interface for managing assets across these platforms. The aim is to enhance the functionality and user interaction on the SkateHive wallet page, with a focus on accessibility and efficient management of digital assets.

#### Requirements:

1. **Hive Section:**
   - **Display Information:**
     - Account balance
     - Voting mana
     - Credits
     - Delegated HP (Hive Power)
   - **Functionalities:**
     - Power up/down Hive
     - Send Hive
     - Send HBD (Hive Backed Dollars)
     - Delegate Hive Power

2. **Ethereum (ETH) Section:**
   - **Display Information:**
     - Wallet address
     - Total balance
     - ETH balance
     - Estimated value of NFTs
   - **Additional Features:**
     - Token balance display
     - Integration of SkateHive OG Banner and Gnars DAO information
     - NFT gallery under Gnars DAO

3. **Swap Functionality:**
   - Enable swapping between Hive and ETH directly from the wallet page.

#### Evaluation Criteria:

- **User Interface Design:** The interface should be clean, intuitive, and visually appealing, facilitating easy navigation and management of blockchain assets.
- **Functionality:** All listed features must be fully functional and tested to ensure reliability and accuracy of transactions and data display.
- **Integration and Performance:** Ensure smooth integration with existing SkateHive infrastructure and APIs. The page should load efficiently and handle transactions securely.

#### Deliverables:

- A fully functional multichain wallet page that integrates both Hive and Ethereum functionalities.
- Detailed documentation on the features implemented, including guidelines on how to use the new wallet functionalities.
- Proper testing and deployment of the wallet page, ensuring compatibility and performance across different devices and browsers.

#### Additional Information:

For any required resources, API access, or if you encounter challenges during the development process, please consult the existing codebase on GitHub or reach out to the project maintainers.

#### Reference: https://skatehive.app/wallet

---
![Screen Recording Apr 18](https://github.com/SkateHive/nextskateapp/assets/116202536/f320587d-515d-4054-88fa-30f0a7bb26d1)

**Comment by webgnar** [comment]
Estimated Vote Value $ would be a good thing to show on the wallet. like $0.20
so people can work on getting their vote value up.
it should show:
 Liquid Hive
 Staked Hive (power).
 Liquid HBD.
Staked HBD

it could also show a Transaction History
It could also show the coingecko Hive Price and HBD price

this is actually the page that I think the user should have to go to, to Claim Rewards, because then it will show the user: "Number go up" in a more visual way. when you click claim rewards, the values of the various tokens (hbd hive or HP) should go up without refreshing the page

**Comment by webgnar** [comment]
we will return to this later
