### ISSUE TITLE
[Bounty] - Implement "My Crew" Filter on SkateHive Homepage

### ISSUE THREAD

**Issue by sktbrd** [SkateHive/nextskateapp#5]
### Description:

We are looking for a developer to complete the implementation of the "My Crew" filter on the SkateHive homepage. This feature is critical for enhancing user engagement by allowing users to view posts exclusively from the people they follow. The "Trending" and "Most Recent" filters are already implemented, and the focus of this task is to finalize the "My Crew" filter.

#### Requirements:

1. **My Crew Filter:**
   - Implement the "My Crew" filter which should display posts only from the users that the logged-in user follows.

#### Evaluation Criteria:

![image](https://github.com/SkateHive/nextskateapp/assets/116202536/62b22454-1031-493c-9a3e-245bb454cb23)

- **Functionality:** The "My Crew" filter should correctly display only the posts from followed users, without any bugs or glitches.
- **Integration:** The new filter must integrate seamlessly with the existing filters and maintain the overall look and feel of the homepage.
- **Performance:** Ensure that the filter works efficiently, with minimal load times and responsive updates when users follow or unfollow others.

#### Deliverables:

- A fully functional "My Crew" filter on the SkateHive homepage.
- Ensure that the filter updates dynamically as users change whom they follow.
- Conduct thorough testing to confirm that the filter works as intended across various user scenarios.

**Comment by webgnar** [comment]
My Crew should be people that I add to a list. 
i follow over 300 people. i only want to see my special list of 15-20 people, including a few people who are not in Skatehive Community

**Comment by webgnar** [comment]
looks good to me
