### ISSUE TITLE
[Bounty] - Develop Comprehensive User Profile Page for SkateHive

### ISSUE THREAD

**Issue by sktbrd** [SkateHive/nextskateapp#6]
### Description:

Create an enhanced user profile page for SkateHive, designed to offer a detailed view of user activities and interactions within the community. This new profile page should include multiple tabs that display user posts, personal information, activity stats, and wallet details, ensuring a rich and engaging user experience.

#### Requirements:

1. **Profile Page Tabs:**
   - **Posts:** Display all posts made by the user.
   - **About:** Include a section for the user's description or bio.
   - **Stats:** Show the user's activity-based scoring with details like:
     - Witness voting activity.
     - HivePower.
     - Last post date.
   - **Wallet:**
     - Integrate Hive Wallet functionalities.
     - Include a feature to swap currencies within the platform.

#### Evaluation Criteria:

- **User Interface Design:** The profile page should be user-friendly, visually appealing, and easy to navigate.
- **Functionality:** Each component of the profile page must be fully functional, displaying accurate and up-to-date information.
- **Integration:** Ensure seamless integration with existing SkateHive functionalities and the overall platform architecture.
- **Performance:** The page should load efficiently and manage data updates smoothly to ensure a good user experience.

#### Deliverables:

- A fully functional user profile page incorporating all required tabs and functionalities.
- Complete integration of the Hive Wallet with both display and transaction capabilities.
- Extensive testing across different devices to ensure functionality and responsive design.

#### Additional Information:

Developers should refer to the existing profile page on SkateHive for layout ideas and integrate features from the old project code available on GitHub. This project requires familiarity with JavaScript frameworks and blockchain technology, specifically related to the Hive ecosystem.

### Bounty: 75 USD

**Comment by darkfuva** [comment]
Intrested
