### ISSUE TITLE
[Bounty] - Implement Weighted Voting Power Feature with Slider for SkateHive

### ISSUE THREAD

**Issue by sktbrd** [SkateHive/nextskateapp#7]
### Description:

This new functionality should include a slider that allows users to choose the percentage of their voting power to use when casting a vote. This feature aims to provide greater flexibility and control over user engagement and content support.

#### Requirements:

1. **Weighted Voting Slider:**
   - Integrate a slider component that allows users to select the percentage of their voting power (from 1% to 100%) they wish to apply to their vote.
   - Ensure that the slider is user-friendly and visually integrates well with the existing voting button.

2. **Functionality:**
   - The voting power selected via the slider should correctly influence the weight of the vote in terms of its impact on content ranking and user rewards.
   - Ensure the system updates the remaining voting power in real-time after each vote.

3. **User Feedback:**
   - Provide clear visual feedback on the selected voting power percentage before submission.
   - Display confirmation messages post-vote to inform users of the successful application of their selected voting power.

#### Evaluation Criteria:

- **User Interface Design:** The slider should be intuitive and seamlessly fit into the current voting interface.
- **Accuracy and Performance:** Voting power adjustments must be precise and reflect immediately in the system without lag or errors.
- **Usability:** Users should find the slider easy to use and understand, with minimal instruction needed.

#### Deliverables:

- A fully functional voting power slider integrated with the existing voting button on SkateHive.
- Backend modifications to handle the weighted voting logic.
- Comprehensive testing to ensure functionality across all platforms and devices.

#### Suggested Bounty: 20 USD

**Comment by darkfuva** [comment]
[SampleSliderUI.webm](https://github.com/SkateHive/nextskateapp/assets/104079433/be884ce2-4607-4b44-a4c3-12ff0d3c2216)

This would be my implementation.

**Comment by webgnar** [comment]
it looks good. does it work?
can you adjust it so the slider appears when the user taps or clicks on the dollar amount?

**Comment by darkfuva** [comment]
Yeah I can do that. It is implemented only on the frontend as of now. 
For end to end implementation can you guide me a little on the following? : -
- Functionality/rules for Voting Power calculation 
- Weight calculation
- Voting power balance calculation

**Comment by webgnar** [comment]
we are reorganizing our bounties. please stand by. =) thank you for your interest. stay following we are going to re-release bounties we just need to get the basic stuff working

**Comment by darkfuva** [comment]
Sure no problem, i would he more than willing to help if you need.
