### ISSUE TITLE
Add emoji picker to cast modal

### ISSUE THREAD

**Issue by sktbrd** [SkateHive/nextskateapp#84]
As a user, i want to be able to include emojis in my casts.

AC:
1. An emoji picker is added to the cast modal
2. Users can scroll, search, and select any emoji
3. When a user clicks an emoji, it's added to cast either where the cursor last was or at the end of the cast

![image](https://github.com/user-attachments/assets/9c3919a3-fed2-47d3-85fa-634e8b5ec84b)

**Comment by sktbrd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add emoji picker to cast modal](https://trello.com/c/L7ZPWED8/45-add-emoji-picker-to-cast-modal)

**Comment by hunxjunedo** [comment]
What's the status ? I'd like to take this one.

**Comment by sktbrd** [comment]
> What's the status ? I'd like to take this one.

feel free to

**Comment by hunxjunedo** [comment]
Alr, please assign
